---
- hosts: varnish
  tasks:
    - name: Deploy key scripts.
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "varnish"
        group: "varnish"
        mode: "u=rx,g=rx,o="
      loop:
        - src: "templates/varnish-foreground.sh.j2"
          dest: "/var/lib/varnish/varnish-foreground.sh"
    - name: Provision the varnish secret
      copy:
        content: "{{ lookup('env', 'VARNISH_SECRET') | default(_secret, true) }}"
        dest: "/etc/varnish/secret"
        owner: "varnish"
        group: "varnish"
        mode: "u=r,g=r,o="
      vars:
        _secret: "{{ flightdeck_varnish.secret | default('secret') }}"
      when:
        - flightdeck_varnish.secretFile is not defined
    - name: Provision the VCL
      copy:
        content: "{{ flightdeck_varnish.vcl | default(flightdeck_varnish_default_vcl) }}"
        dest: "/etc/varnish/default.vcl"
        owner: "varnish"
        group: "varnish"
        mode: "u=r,g=r,o="
      when:
        - flightdeck_varnish.vclPath is not defined

